language:
  - cpp
compiler:
  - gcc
env:
  global:
    - secure: "b8HEFYjBGg0P/SsAZnZwooxv80dcIWAZXlrA8nFPdz6OIulmpnr3fzJKc4p4HAxCqKttbtL8QNwTV1XtFjEh9cgCcqrScpXUfYkxn9brtwtAVT5wsLwYFg2Q1MrdVz1z0BkOwl/RTcGco2MmxHUhPOZ4KqtoZja0m8VHljY2KpiQIbeykm1YUbao9IvNNm9uX86++0of9kdORA3W3LYyAo6GMYHKef754DORv+307vhZs/x5Ikrn3mClrkgRtIGHBCg3qpJoqMmfh+YXO1hyNQAkzDEtqYTh/7qkiacmQx82yi2D9XsvEfq1WmrAX8DPGOYciqTIX39xBzMlgkv2F8Fm+y71yPkNPNSb9VNgBGQvoQ36QRDHZvILdOT3vj2xlILLQ62+JXk/vy5ePImqISv/9hO9FVkCCt7DnublUnAp+WXw7pHOWuaEPnSkC+2p+KJ2+d2UV24TmC1fTHn62V5/rOZbu/dHkxhJCi5SLRTqtphzAXtBwRtWZNbW/Wu2P6oZQzDl4+Rqe/jCeKctRO7zVgp+GIStYBiNOmfyVfguRy8yknOxkRVXDMslojDbujq9qRJrRHXGM1ETGU0BnYuPPO0NyAbNxwoVGRRWsEYdC8kwOpAW24FcLkikFIyy1Cn0ea57tCELiULYVsN8/KWj5RXzXz7IAd4ldgLKtwM="
script: source .travis.sh
sudo: required
after_success:
  - set +x
  - export GIT_COMMITTER_NAME=$GIT_NAME
  - export GIT_COMMITTER_EMAIL=$GIT_EMAIL
  - export GIT_AUTHOR_NAME=$GIT_NAME
  - export GIT_AUTHOR_EMAIL=$GIT_EMAIL
  - echo "TRAVIS_PULL_REQUEST=$TRAVIS_PULL_REQUEST TRAVIS_BRANCH=$TRAVIS_BRANCH"
  - if [ "$TRAVIS_PULL_REQUEST" == "false" -a "$TRAVIS_BRANCH" == "master" ]; then cd ~/;            fi
  - if [ "$TRAVIS_PULL_REQUEST" == "false" -a "$TRAVIS_BRANCH" == "master" ]; then git clone --branch gh-pages https://github.com/$TRAVIS_REPO_SLUG editor;  fi
  - if [ "$TRAVIS_PULL_REQUEST" == "false" -a "$TRAVIS_BRANCH" == "master" ]; then cd editor;           fi
