language:
  - cpp
compiler:
  - gcc
env:
  global:
    - secure: "b8HEFYjBGg0P/SsAZnZwooxv80dcIWAZXlrA8nFPdz6OIulmpnr3fzJKc4p4HAxCqKttbtL8QNwTV1XtFjEh9cgCcqrScpXUfYkxn9brtwtAVT5wsLwYFg2Q1MrdVz1z0BkOwl/RTcGco2MmxHUhPOZ4KqtoZja0m8VHljY2KpiQIbeykm1YUbao9IvNNm9uX86++0of9kdORA3W3LYyAo6GMYHKef754DORv+307vhZs/x5Ikrn3mClrkgRtIGHBCg3qpJoqMmfh+YXO1hyNQAkzDEtqYTh/7qkiacmQx82yi2D9XsvEfq1WmrAX8DPGOYciqTIX39xBzMlgkv2F8Fm+y71yPkNPNSb9VNgBGQvoQ36QRDHZvILdOT3vj2xlILLQ62+JXk/vy5ePImqISv/9hO9FVkCCt7DnublUnAp+WXw7pHOWuaEPnSkC+2p+KJ2+d2UV24TmC1fTHn62V5/rOZbu/dHkxhJCi5SLRTqtphzAXtBwRtWZNbW/Wu2P6oZQzDl4+Rqe/jCeKctRO7zVgp+GIStYBiNOmfyVfguRy8yknOxkRVXDMslojDbujq9qRJrRHXGM1ETGU0BnYuPPO0NyAbNxwoVGRRWsEYdC8kwOpAW24FcLkikFIyy1Cn0ea57tCELiULYVsN8/KWj5RXzXz7IAd4ldgLKtwM="
script: source .travis.sh
sudo: required
