#ifndef CNOID_MODELEDITPLUGIN_EXPORTDECL_H_INCLUDED
# define CNOID_MODELEDITPLUGIN_EXPORTDECL_H_INCLUDED

# if defined _WIN32 || defined __CYGWIN__
#  define CNOID_MODELEDITPLUGIN_DLLIMPORT __declspec(dllimport)
#  define CNOID_MODELEDITPLUGIN_DLLEXPORT __declspec(dllexport)
#  define CNOID_MODELEDITPLUGIN_DLLLOCAL
# else
#  if __GNUC__ >= 4
#   define CNOID_MODELEDITPLUGIN_DLLIMPORT __attribute__ ((visibility("default")))
#   define CNOID_MODELEDITPLUGIN_DLLEXPORT __attribute__ ((visibility("default")))
#   define CNOID_MODELEDITPLUGIN_DLLLOCAL  __attribute__ ((visibility("hidden")))
#  else
#   define CNOID_MODELEDITPLUGIN_DLLIMPORT
#   define CNOID_MODELEDITPLUGIN_DLLEXPORT
#   define CNOID_MODELEDITPLUGIN_DLLLOCAL
#  endif
# endif

# ifdef CNOID_MODELEDITPLUGIN_STATIC
#  define CNOID_MODELEDITPLUGIN_DLLAPI
#  define CNOID_MODELEDITPLUGIN_LOCAL
# else
#  ifdef CnoidModelEditPlugin_EXPORTS
#   define CNOID_MODELEDITPLUGIN_DLLAPI CNOID_MODELEDITPLUGIN_DLLEXPORT
#  else
#   define CNOID_MODELEDITPLUGIN_DLLAPI CNOID_MODELEDITPLUGIN_DLLIMPORT
#  endif
#  define CNOID_MODELEDITPLUGIN_LOCAL CNOID_MODELEDITPLUGIN_DLLLOCAL
# endif

#endif

#ifdef CNOID_EXPORT
# undef CNOID_EXPORT
#endif
#define CNOID_EXPORT CNOID_MODELEDITPLUGIN_DLLAPI
